feat: beanstalk test

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -20,3 +20,23 @@ workflows:
         inputs:
         - command: test
     - deploy-to-bitrise-io@1.3.3: {}
+    - script@1.1.4:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # write your script here
+            mkdir $HOME/.aws
+            touch $HOME/.aws/config
+            chmod 600 $HOME/.aws/config
+            echo "[profile eb-cli]" > $HOME/.aws/config
+            echo "aws_access_key_id=$aws_access_key_id" >> $HOME/.aws/config
+            echo "aws_secret_access_key=$aws_secret_access_key" >> $HOME/.aws/config
+            cat $HOME/.aws/config
+            sudo pip install awsebcli
+
+            eb deploy
